
###
POST http://127.0.0.1:5000/app_dac/init_dac HTTP/1.1
###
POST http://127.0.0.1:5000/app_dac/get_single_adc_value HTTP/1.1
content-type: application/json

{
    "voltage_card": 0, 
    "channel": 0
}
###
GET http://127.0.0.1:5000/app_dac/get_voltage HTTP/1.1
###
POST http://127.0.0.1:5000/app_dac/set_dac_value HTTP/1.1
content-type: application/json

{
    "voltage": 10,
    "channel": 0
}
